# ZannenDongle_uf2 board-specific Kconfig fragment (applied on top of defconfig)

CONFIG_USB_DEVICE_MANUFACTURER="Zannen"
CONFIG_USB_DEVICE_PRODUCT="SlimeNRF Receiver ZannenDongle"

# RGB LED color mode
CONFIG_LED_RGB_COLOR=y

# MPSL FEM GPIO driver for RFX2401C (simple 2-pin FEM)
CONFIG_MPSL=y
CONFIG_MPSL_FEM=y
CONFIG_MPSL_FEM_SIMPLE_GPIO=y
